# To train the Object detection Model:

In [1]:
from ultralytics import YOLO

# # Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# # Train the model with 2 GPUs
results = model.train(data='data.yaml', epochs=200, imgsz=640) 


100%|██████████| 6.23M/6.23M [00:00<00:00, 19.8MB/s]

c:\Users\muska\Desktop\Automatic-Number-Plate-Recognition--ANPR--2\ultralytics\nn\tasks.py:341: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this e

# Test Object Detection Model:

In [1]:
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('runs/detect/train/weights/best.pt')

# Run inference on 'bus.jpg' with arguments
source=r'C:\Users\muska\Desktop\Automatic-Number-Plate-Recognition--ANPR--2\dataset\test\images'
model.predict(source, save=True, imgsz=320, conf=0.2)


c:\Users\muska\Desktop\Automatic-Number-Plate-Recognition--ANPR--2\ultralytics\nn\tasks.py:341: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(attempt_downl

[tensor([], size=(0, 6)),
 tensor([[2.26000e+02, 1.10000e+02, 2.54000e+02, 1.18000e+02, 2.44327e-01, 0.00000e+00]]),
 tensor([[ 50.00000, 130.00000, 163.00000, 193.00000,   0.93295,   0.00000]]),
 tensor([[292.00000, 232.00000, 464.00000, 378.00000,   0.87136,   0.00000]]),
 tensor([[ 76.00000,  75.00000, 304.00000, 202.00000,   0.89667,   0.00000]]),
 tensor([], size=(0, 6)),
 tensor([], size=(0, 6)),
 tensor([[1.53000e+02, 1.59000e+02, 2.23000e+02, 1.98000e+02, 9.29527e-01, 0.00000e+00],
         [3.08000e+02, 3.81000e+02, 3.99000e+02, 4.00000e+02, 2.55290e-01, 0.00000e+00]]),
 tensor([[355.00000, 170.00000, 388.00000, 185.00000,   0.51471,   0.00000]]),
 tensor([[115.00000, 157.00000, 476.00000, 236.00000,   0.88086,   0.00000]]),
 tensor([], size=(0, 6)),
 tensor([[117.00000, 150.00000, 150.00000, 168.00000,   0.89441,   0.00000]]),
 tensor([[240.00000, 183.00000, 284.00000, 203.00000,   0.65879,   0.00000]]),
 tensor([[276.00000, 118.00000, 343.00000, 135.00000,   0.78982,   0.000

# Recognize License plate after Detecting  using easy-ocr

In [1]:
#!pip install easyocr

In [ ]:
!python predict_modified.py model='runs/detect/train/weights/best.pt' source='C:\Users\muska\Desktop\Automatic-Number-Plate-Recognition--ANPR--2\IMG_0.mp4'

[[[137 206 189]
  [128 197 180]
  [113 175 159]
  ...
  [196 221 227]
  [154 179 185]
  [104 129 135]]

 [[128 197 180]
  [139 208 191]
  [135 197 181]
  ...
  [212 237 243]
  [145 170 176]
  [ 90 115 121]]

 [[102 160 144]
  [123 181 165]
  [137 190 175]
  ...
  [182 202 209]
  [129 149 156]
  [ 93 113 120]]

 ...

 [[138 132 127]
  [138 132 127]
  [138 132 127]
  ...
  [172 166 161]
  [172 166 161]
  [172 166 161]]

 [[138 132 127]
  [138 132 127]
  [138 132 127]
  ...
  [172 166 161]
  [172 166 161]
  [172 166 161]]

 [[138 132 127]
  [138 132 127]
  [138 132 127]
  ...
  [172 166 161]
  [172 166 161]
  [172 166 161]]]

[[[138 205 188]
  [138 205 188]
  [125 185 169]
  ...
  [221 244 250]
  [167 190 196]
  [105 128 134]]

 [[113 180 163]
  [133 200 183]
  [139 199 183]
  ...
  [214 237 243]
  [155 178 184]
  [ 98 121 127]]

 [[ 91 141 127]
  [109 159 145]
  [129 177 163]
  ...
  [163 179 186]
  [134 150 157]
  [105 121 128]]

 ...

 [[138 132 127]
  [138 132 127]
  [138 132 127]
  .

Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
Ultralytics YOLOv8.0.3  Python-3.12.1 torch-2.5.0+cpu CPU
c:\Users\muska\Desktop\Automatic-Number-Plate-Recognition--ANPR--2\ultralytics\nn\tasks.py:303: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you do


  [114 110 120]]

 [[ 76  91  89]
  [ 75  90  88]
  [ 74  89  87]
  ...
  [105 104 114]
  [108 104 114]
  [108 104 114]]

 [[ 76  91  89]
  [ 75  90  88]
  [ 74  89  87]
  ...
  [ 99 101 108]
  [100 100 107]
  [101 101 108]]

 ...

 [[114 114 114]
  [114 114 114]
  [114 114 114]
  ...
  [169 163 158]
  [169 163 158]
  [169 163 158]]

 [[114 114 114]
  [114 114 114]
  [114 114 114]
  ...
  [170 164 159]
  [170 164 159]
  [170 164 159]]

 [[114 114 114]
  [114 114 114]
  [114 114 114]
  ...
  [172 166 161]
  [172 166 161]
  [172 166 161]]]
"TnIOBQ1586
[[[ 76  91  89]
  [ 76  91  89]
  [ 76  91  89]
  ...
  [109 108 118]
  [115 111 121]
  [114 110 120]]

 [[ 76  91  89]
  [ 76  91  89]
  [ 76  91  89]
  ...
  [105 104 114]
  [108 104 114]
  [108 104 114]]

 [[ 77  92  90]
  [ 77  92  90]
  [ 76  91  89]
  ...
  [ 99 101 108]
  [101 101 108]
  [101 101 108]]

 ...

 [[119 119 119]
  [119 119 119]
  [119 119 119]
  ...
  [195 189 184]
  [195 189 184]
  [195 189 184]]

 [[119 119 119]
  [11

: 